"""init1

Revision ID: cc4c9fb96066
Revises: 2d0a529ce08a
Create Date: 2023-07-07 22:26:03.505468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4c9fb96066'
down_revision = '2d0a529ce08a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
