"""initial

Revision ID: a73fd5b1c5c3
Revises: cfd5c2fafdaf
Create Date: 2023-07-05 18:30:33.680269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73fd5b1c5c3'
down_revision = 'cfd5c2fafdaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'progression_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'progression_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
