"""init1

Revision ID: 2d0a529ce08a
Revises: 49f5f6653ea4
Create Date: 2023-07-07 22:18:51.540239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0a529ce08a'
down_revision = '49f5f6653ea4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
