"""initial

Revision ID: cfd5c2fafdaf
Revises: 27087eff290d
Create Date: 2023-07-05 18:28:16.674724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfd5c2fafdaf'
down_revision = '27087eff290d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
